export const runtime = "nodejs";

import { jsPDF } from "jspdf";
import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
  BorderStyle,
  // TableRow,
  // TableCell,
  // Table,
  // WidthType,
} from "docx";

// Parses markdown-ish content into sections: ## heading, - bullet, plain text
function parseContent(content: string) {
  const lines = content.split("\n").filter((l) => l.trim());
  const sections: Array<{
    type: "heading" | "bullet" | "text";
    value: string;
  }> = [];

  for (const line of lines) {
    const trimmed = line.trim();
    if (trimmed.startsWith("## ")) {
      sections.push({ type: "heading", value: trimmed.slice(3) });
    } else if (trimmed.startsWith("# ")) {
      sections.push({ type: "heading", value: trimmed.slice(2) });
    } else if (trimmed.startsWith("- ") || trimmed.startsWith("• ")) {
      sections.push({ type: "bullet", value: trimmed.slice(2) });
    } else if (trimmed) {
      sections.push({ type: "text", value: trimmed });
    }
  }

  return sections;
}

function generatePDF(title: string, content: string): Buffer {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 20;
  const usableW = pageW - margin * 2;
  let y = margin;

  function checkPage(needed = 10) {
    if (y + needed > pageH - margin) {
      doc.addPage();
      y = margin;
    }
  }

  // Header bar
  doc.setFillColor(30, 30, 32);
  doc.rect(0, 0, pageW, 16, "F");
  doc.setTextColor(110, 231, 183); // mint accent
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.text("KAYTEE FURNITURES", margin, 10);
  doc.setTextColor(113, 113, 122);
  doc.text("Mood Board Brief", pageW - margin, 10, { align: "right" });

  y = 28;

  // Title
  doc.setTextColor(20, 20, 20);
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  const titleLines = doc.splitTextToSize(title, usableW);
  doc.text(titleLines, margin, y);
  y += titleLines.length * 9 + 4;

  // Divider
  doc.setDrawColor(110, 231, 183);
  doc.setLineWidth(0.8);
  doc.line(margin, y, margin + 40, y);
  y += 8;

  // Date
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(113, 113, 122);
  doc.text(
    new Date().toLocaleDateString("en-GB", { dateStyle: "long" }),
    margin,
    y,
  );
  y += 10;

  // Content
  const sections = parseContent(content);

  for (const section of sections) {
    if (section.type === "heading") {
      checkPage(14);
      y += 4;
      doc.setFontSize(12);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(30, 30, 32);
      doc.text(section.value.toUpperCase(), margin, y);
      y += 2;
      doc.setDrawColor(228, 228, 231);
      doc.setLineWidth(0.3);
      doc.line(margin, y, pageW - margin, y);
      y += 6;
    } else if (section.type === "bullet") {
      checkPage(8);
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(40, 40, 40);
      const bulletLines = doc.splitTextToSize(
        `• ${section.value}`,
        usableW - 4,
      );
      doc.text(bulletLines, margin + 2, y);
      y += bulletLines.length * 5.5 + 1;
    } else {
      checkPage(8);
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(60, 60, 60);
      const textLines = doc.splitTextToSize(section.value, usableW);
      doc.text(textLines, margin, y);
      y += textLines.length * 5.5 + 3;
    }
  }

  // Footer on each page
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFillColor(248, 248, 248);
    doc.rect(0, pageH - 12, pageW, 12, "F");
    doc.setFontSize(7);
    doc.setTextColor(160, 160, 160);
    doc.setFont("helvetica", "normal");
    doc.text(
      "Generated by Kaytee Furnitures · Interior Design Brief",
      margin,
      pageH - 5,
    );
    doc.text(`${i} / ${totalPages}`, pageW - margin, pageH - 5, {
      align: "right",
    });
  }

  return Buffer.from(doc.output("arraybuffer"));
}

async function generateDOCX(title: string, content: string): Promise<Buffer> {
  const sections = parseContent(content);

  const children = [
    new Paragraph({
      text: title,
      heading: HeadingLevel.TITLE,
      spacing: { after: 200 },
    }),
    new Paragraph({
      children: [
        new TextRun({
          text: new Date().toLocaleDateString("en-GB", { dateStyle: "long" }),
          color: "71717A",
          size: 18,
        }),
      ],
      spacing: { after: 400 },
    }),
    ...sections.map((section) => {
      if (section.type === "heading") {
        return new Paragraph({
          text: section.value,
          heading: HeadingLevel.HEADING_2,
          spacing: { before: 300, after: 100 },
        });
      } else if (section.type === "bullet") {
        return new Paragraph({
          text: section.value,
          bullet: { level: 0 },
          spacing: { after: 80 },
        });
      } else {
        return new Paragraph({
          children: [new TextRun({ text: section.value, size: 22 })],
          spacing: { after: 120 },
        });
      }
    }),
    new Paragraph({
      children: [
        new TextRun({
          text: "Generated by Kaytee Furnitures · Interior Design Brief",
          color: "A1A1AA",
          size: 16,
          italics: true,
        }),
      ],
      alignment: AlignmentType.CENTER,
      spacing: { before: 600 },
      border: {
        top: { style: BorderStyle.SINGLE, size: 1, color: "E4E4E7" },
      },
    }),
  ];

  const doc = new Document({
    styles: {
      default: {
        document: {
          run: { font: "Calibri", size: 22 },
        },
      },
    },
    sections: [{ children }],
  });

  return await Packer.toBuffer(doc);
}

export async function POST(req: Request) {
  const { title, content, format } = await req.json();

  if (!content?.trim()) {
    return new Response("content is required", { status: 400 });
  }
  if (!["pdf", "docx"].includes(format)) {
    return new Response("format must be pdf or docx", { status: 400 });
  }

  const safeTitle = (title ?? "Design Brief").trim();

  try {
    if (format === "pdf") {
      const buffer = generatePDF(safeTitle, content);
      const arrayBuffer = buffer.buffer.slice(
        buffer.byteOffset,
        buffer.byteOffset + buffer.byteLength,
      ) as ArrayBuffer;
      return new Response(arrayBuffer, {
        headers: {
          "Content-Type": "application/pdf",
          "Content-Disposition": `attachment; filename="${safeTitle}.pdf"`,
        },
      });
    } else {
      const buffer = await generateDOCX(safeTitle, content);
      const arrayBuffer = buffer.buffer.slice(
        buffer.byteOffset,
        buffer.byteOffset + buffer.byteLength,
      ) as ArrayBuffer;
      return new Response(arrayBuffer, {
        headers: {
          "Content-Type":
            "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
          "Content-Disposition": `attachment; filename="${safeTitle}.docx"`,
        },
      });
    }
  } catch (err) {
    return new Response((err as Error).message, { status: 500 });
  }
}
